# Generated by Django 4.0.4 on 2022-05-17 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(4)])),
                ('description', models.CharField(max_length=2000, validators=[django.core.validators.MinLengthValidator(30)])),
                ('startBid', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)])),
                ('image', models.ImageField(upload_to='')),
                ('activelisting', models.BooleanField(default=True)),
                ('timePosted', models.DateTimeField(auto_now_add=True)),
                ('itemCategory', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctionitems', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
