# Generated by Django 4.0.4 on 2022-05-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_usercomment_userbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionitem',
            old_name='user1',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userbid',
            old_name='user3',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usercomment',
            old_name='user2',
            new_name='user',
        ),
    ]
