# Generated by Django 4.0.4 on 2022-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_user1_auctionitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
