# Generated by Django 4.0.4 on 2022-05-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionitem',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='auctionitem',
            old_name='watchlist',
            new_name='watchedby',
        ),
    ]
