# Generated by Django 4.0.4 on 2022-05-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_user_auctionitem_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(upload_to='cs50/ebay/uploads/'),
        ),
    ]
